# Generated by Django 5.2.8 on 2025-12-30 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.CharField(max_length=100)),
                ('punishment', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fee_alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=100)),
                ('Fee', models.IntegerField()),
                ('Username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('DoB', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.BigIntegerField()),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='motivated_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='diet_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_shift', models.CharField(max_length=100)),
                ('planname', models.CharField(max_length=100)),
                ('category_type', models.CharField(max_length=100)),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='assign_trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('date', models.DateField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='workout_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('workout', models.CharField(max_length=100)),
                ('time_per_day', models.TimeField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='workoutplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planname', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='')),
                ('details', models.CharField(max_length=100)),
                ('DIET_PLAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.diet_plan')),
            ],
        ),
    ]
