# Generated by Django 5.2.8 on 2025-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_motivated_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
