# Generated by Django 5.2.6 on 2026-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
