# Generated by Django 5.2.6 on 2026-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_table_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='user_request',
        ),
        migrations.AddField(
            model_name='diet_plan',
            name='discription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet_plan',
            name='target_goal',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout_plan',
            name='plan_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
