# Generated by Django 5.2.6 on 2026-02-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_request_user_request_diet_plan_discription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dietplan', models.CharField(max_length=1000)),
                ('work_out', models.CharField(max_length=1000)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
    ]
