# Generated by Django 5.2.6 on 2026-02-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_diet_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='FROM',
            new_name='FROM_ID',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='TO',
            new_name='TO_ID',
        ),
    ]
