# Generated by Django 5.2.6 on 2026-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_from_chat_from_id_rename_to_chat_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_trainer',
            name='view_status',
            field=models.BooleanField(default=False),
        ),
    ]
